### ISSUE TITLE
Wiki permission

### ISSUE THREAD

**Issue by ickc** [Astro250/Sping2017#1]
Hi, @aepolin,

Will you consider [opening up the Wiki's permission](https://help.github.com/articles/changing-access-permissions-for-wikis/) so we can also put relevant info there?

For example, one potentially useful info is the email @nugent68 sent earlier (and by the way, I've trouble accessing the urls: `Your account was created and is now pending administrator approval.`):

> Hi Sinan,
> 
> so I think the class would be fine for upper-level undergraduates with some computing experience (python, C, C++, or Fortran, etc.) in-hand. We work on getting you up to speed on using the NERSC supercomputers to do simulations and analysis with a variety of parallel codes. The goal is to help you use the high performance computing to do research for your thesis.\
> \
> Here's a quick breakdown, not sure the links will work for you, but the descriptions should be enough to see what is what:
> 
> [*Introduction of HPC for Astrophysicists*](https://c3.lbl.gov/redmine/attachments/download/1/intro.pptx)
> 
> 
> [*Description of NERSC*](https://c3.lbl.gov/redmine/attachments/download/2/NERSC.pptx)
> 
> 
> [*Unix @ NERSC 1*](https://c3.lbl.gov/redmine/attachments/download/3/unix_at_nersc_1.pptx)
> 
> 
> [*Unix @ NERSC 2*](https://c3.lbl.gov/redmine/attachments/download/4/unix_at_nersc_2.ppt)
> 
> 
> [*Bash Overview*](https://c3.lbl.gov/redmine/attachments/download/5/Bash.ppt)
> 
> (So the above are all how to get set up to use NERSC)
> 
> Git work came from [*http://gitimmersion.com/*](http://gitimmersion.com/)
> 
> (Git for backing up code)
> 
> Here is a good overall description of how to use ssh. [*https://wiki.archlinux.org/index.php/SSH\_keys*](https://wiki.archlinux.org/index.php/SSH_keys)
> 
> 
> The best write-up for using PBS for submitting jobs on edison can be found [*here*](http://www.nersc.gov/users/computational-systems/edison/running-jobs/batch-jobs/)
> 
> 
> And for monitoring and modifying jobs on edison look [*here*](http://www.nersc.gov/users/computational-systems/edison/running-jobs/monitoring-jobs/)
> 
> (logging into NERSC, submitting jobs and monitoring them)
> 
> [*First and Second Brush with OpenMP*](https://c3.lbl.gov/redmine/attachments/download/7/openmp_2.ppt)
> 
> 
> [*Makefiles*](https://c3.lbl.gov/redmine/attachments/download/8/UnixMakefiles.ppt)
> 
> 
> [*First*](https://c3.lbl.gov/redmine/attachments/download/9/mpi_1.pdf) and [*Second*](https://c3.lbl.gov/redmine/attachments/download/10/mpi_2.pdf) lecures on MPI. You can find the codes we played with here: /project/projectdirs/astro250/code/mpi
> 
> 
> [*Edison & aprun*](https://c3.lbl.gov/redmine/attachments/download/11/NERSC_edison_aprun.pptx)
> 
> (how to write and run parallel codes - will add in vectorization and shift to slurm)
> 
> [*Gunther Weber's talk on VisIt*](https://c3.lbl.gov/redmine/attachments/download/12/Astronomy250.pptx)
> 
> (Some visualization work - will be replaced now by yt)
> 
> [*Zarija Lukic's talk on Gadget*](https://c3.lbl.gov/redmine/attachments/download/13/nbody-gadget.pdf)
> 
> 
> [*Ann Almgren's Talk on CASTRO*](https://c3.lbl.gov/redmine/attachments/download/14/Astro_250_Almgren.ppt)
> 
> 
> [*An Extra Talk by Ann on AMR*](https://c3.lbl.gov/redmine/attachments/download/15/HIPACC_July2011.pdf)
> 
> 
> [*Fernando Perez's talk on Python: performance and parallelism*](https://c3.lbl.gov/redmine/attachments/download/16/python-perf.pdf)
> 
> 
> [*Rollin Thomas' talk on SYNAPPS*](https://c3.lbl.gov/redmine/attachments/download/17/thomas_2015.pdf)
> 
> (Example high performance, parallel codes for astro)
> 
> [*Yushu Yao's talk on SciDB*](https://c3.lbl.gov/redmine/attachments/download/19/SciDB.pptx)
> 
> (parallel db's - will be replaced with lectures on HDF5)
> 
> [*Neuromorphic Computing*](https://c3.lbl.gov/redmine/attachments/download/20/neuro_astro250.pptx)
> 
> 
> [*IBM's Talk on NC*](https://c3.lbl.gov/redmine/attachments/download/21/IBM_NC.mp4)
> 
> (Next gen computing)
> 
> Cheers,  
> Peter

**Comment by nugent68** [comment]
Just set it up for everyone today.

Cheers,

Peter
