### ISSUE TITLE
Wiki broken link on "Woo-Sun's Parallel Debugger talk"

### ISSUE THREAD

**Issue by ickc** [Astro250/Sping2017#2]
In [commit 35f6fb4](https://github.com/Astro250/Sping2017/wiki/Home/35f6fb4aee3a4005067779f78f96e2de9ec1b8ed) of the wiki 

> Woo-Sun's Parallel Debugger talk can be found here.

which points to https://c3.lbl.gov/nugent/talks/astro250/ParallelDebuggingTools-201702.ppt

but when clicked into, it said

> Not Found
>
> The requested URL /nugent/talks/astro250/ParallelDebuggingTools-201702.ppt was not found on this server.

I found the pdf in https://www.nersc.gov/assets/Uploads/ParallelDebuggingTools-201702.pdf , but the ppt would be useful too.

**Comment by nugent68** [comment]
Made the appropriate link to the pdf. No ppt for this one, though I'll try to find it.
